# Use new trusty images, should yield newer compilers and packages
# ref: https://github.com/genbattle/dkm.git
sudo: required
dist: Rtrusty
language: cpp

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
			- cmake
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
			- cmake
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
			- cmake
      env: COMPILER=clang++-3.7

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - cd test
  - (mkdir build && cd build && cmake ..)
script:
  - cmake --version
  - pwd
  - make